In [6]:
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns

# Force reset backend just in case
import matplotlib
matplotlib.use('module://matplotlib_inline.backend_inline')


In [7]:
#Importing Packages
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
%matplotlib

Using matplotlib backend: agg


In [8]:
#Reading and Studying the Dataset
iris = pd.read_csv("iris.data", header=None)
iris

,0,1,2,3,4
0,5.1,3.5,1.4,0.2,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Iris-virginica
146,6.3,2.5,5.0,1.9,Iris-virginica
147,6.5,3.0,5.2,2.0,Iris-virginica
148,6.2,3.4,5.4,2.3,Iris-virginica


In [9]:
iris.columns = ['SL', 'SW', 'PL', 'PW', 'Flower Type']
iris

,SL,SW,PL,PW,Flower Type
0,5.1,3.5,1.4,0.2,Iris-setosa
1,4.9,3.0,1.4,0.2,Iris-setosa
2,4.7,3.2,1.3,0.2,Iris-setosa
3,4.6,3.1,1.5,0.2,Iris-setosa
4,5.0,3.6,1.4,0.2,Iris-setosa
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,Iris-virginica
146,6.3,2.5,5.0,1.9,Iris-virginica
147,6.5,3.0,5.2,2.0,Iris-virginica
148,6.2,3.4,5.4,2.3,Iris-virginica


In [10]:
iris.isnull().sum()

,0
SL,0
SW,0
PL,0
PW,0
Flower Type,0


In [11]:
iris.dtypes

,0
SL,float64
SW,float64
PL,float64
PW,float64
Flower Type,object


In [13]:
#Encoding
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
iris['Flower Type'] = le.fit_transform(iris['Flower Type'])
iris

,SL,SW,PL,PW,Flower Type
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0
...,...,...,...,...,...
145,6.7,3.0,5.2,2.3,2
146,6.3,2.5,5.0,1.9,2
147,6.5,3.0,5.2,2.0,2
148,6.2,3.4,5.4,2.3,2


In [14]:
iris['Flower Type'].unique()

array([0, 1, 2])

In [15]:
le.inverse_transform([0,1,2])

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [16]:
ip=iris.drop('Flower Type',axis=1)
op=iris['Flower Type']

In [17]:
from keras.utils import to_categorical
op=to_categorical(op, 3)

In [18]:
op

array([[1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0

In [19]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(ip,op,test_size=0.2,random_state=42)

In [20]:
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam

In [22]:
model = Sequential()
model.add(Dense(20, input_dim=4, activation='relu'))

model.add(Dense(35, activation='relu'))
model.add(Dense(15, activation='relu'))

model.add(Dense(3, activation='softmax'))
model.compile(Adam(learning_rate=0.01), loss='categorical_crossentropy', metrics=['accuracy'])

In [23]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_4 (Dense)                 │ (None, 20)             │           100 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 35)             │           735 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ (None, 15)             │           540 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_7 (Dense)                 │ (None, 3)              │            48 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,423 (5.56 KB)

 Trainable params: 1,423 (5.56 KB)

 Non-trainable params: 0 (0.00 B)

In [24]:
model.fit(x_train,y_train,validation_data=(x_test,y_test),epochs=15)

Epoch 1/15
4/4 ━━━━━━━━━━━━━━━━━━━━ 2s 136ms/step - accuracy: 0.3583 - loss: 1.0313 - val_accuracy: 0.8667 - val_loss: 0.7311
Epoch 2/15
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7417 - loss: 0.6905 - val_accuracy: 0.7333 - val_loss: 0.5580
Epoch 3/15
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.7750 - loss: 0.4895 - val_accuracy: 0.7000 - val_loss: 0.4294
Epoch 4/15
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8083 - loss: 0.3874 - val_accuracy: 0.8333 - val_loss: 0.4082
Epoch 5/15
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step - accuracy: 0.8583 - loss: 0.3465 - val_accuracy: 0.8000 - val_loss: 0.3103
Epoch 6/15
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.8417 - loss: 0.3352 - val_accuracy: 0.8333 - val_loss: 0.2987
Epoch 7/15
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.9417 - loss: 0.2427 - val_accuracy: 0.9333 - val_loss: 0.2228
Epoch 8/15
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step - accuracy: 0.9583 - loss: 0.2152 - val_accuracy: 1.0000 - val_loss: 0.1842

In [25]:
pred = model.predict(x_test)
pred

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 140ms/step


array([[7.5838563e-04, 9.4320762e-01, 5.6033880e-02],
       [9.9927449e-01, 7.2551414e-04, 1.3033987e-08],
       [1.5998152e-09, 7.5293047e-04, 9.9924707e-01],
       [7.3754980e-04, 9.1483474e-01, 8.4427670e-02],
       [4.9613876e-04, 9.7569317e-01, 2.3810586e-02],
       [9.9861366e-01, 1.3863015e-03, 4.6777494e-08],
       [7.1894871e-03, 9.9044663e-01, 2.3638583e-03],
       [2.5959262e-05, 3.2454401e-01, 6.7543000e-01],
       [2.5735618e-04, 7.1966761e-01, 2.8007498e-01],
       [3.7111321e-03, 9.9206662e-01, 4.2222477e-03],
       [5.9241276e-05, 4.1140103e-01, 5.8853966e-01],
       [9.9806005e-01, 1.9398420e-03, 1.6273081e-07],
       [9.9951714e-01, 4.8280900e-04, 1.0196429e-08],
       [9.9810416e-01, 1.8956888e-03, 1.3693672e-07],
       [9.9925268e-01, 7.4730872e-04, 3.0938413e-08],
       [7.1617798e-04, 9.5708162e-01, 4.2202160e-02],
       [1.4496672e-07, 6.6536143e-03, 9.9334615e-01],
       [3.3640368e-03, 9.8754960e-01, 9.0863528e-03],
       [8.5675064e-04, 8.823

In [26]:
p = np.argmax(pred, axis=1)
p

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [27]:
y_test

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [28]:
y = np.argmax(y_test, axis=1)
y

array([1, 0, 2, 1, 1, 0, 1, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2, 1, 1, 2, 0, 2,
       0, 2, 2, 2, 2, 2, 0, 0])

In [29]:
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score
ac = accuracy_score(y, p)
rc = recall_score(y, p, average='micro')
pc = precision_score(y, p, average='micro')
f1 = f1_score(y, p, average='micro')

print('Accuracy:', ac)
print('Recall:', rc)
print('Precision:', pc)
print('F1 Score:', f1)

Accuracy: 1.0
Recall: 1.0
Precision: 1.0
F1 Score: 1.0
