# NLP - Natural Language Processing
<pre>
    <b>
        It is a branch of AI that enables computers to understand, interprets, analyse, and generate human language
        Types:
            - NLU : Natural Language Understanding
            - NLG : Natural Language Generation
        Applications:
            - ChatBots, AI Assistance, Spam email fillter
        Basic terminologies:
            - Corpus: Large and structured set of text used for NLP
            - Document: A Line of sentence
            - Words: 
            - Vocabulary: No. of unique words used 
            - Vector/Vectorizer: It is used for to show the importance of the word
            - Stopwords: Commonly used words
            - Tokens: The fundamental building blocks of text
</pre>
### Steps involved in NLP:
<pre>
    (Tokenization) --> (Stemming) --> (Lematization) --> (POS tags) --> (NER: Named Entity Recognition) --> (Chenking)
</pre>

       [ Raw Input Text ]
               │
               ▼
      ┌─────────────────┐
      │  Tokenization   │  (Splits text into individual words/tokens)
      └─────────────────┘
               │
               ▼
      ┌─────────────────┐
      │    Stemming     │  (Chops off word endings crudely)
      └─────────────────┘
               │
               ▼
      ┌─────────────────┐
      │  Lemmatization  │  (Reduces words to base dictionary form)
      └─────────────────┘
               │
               ▼
      ┌─────────────────┐
      │    POS Tags     │  (Identifies grammar roles like Noun, Verb)
      └─────────────────┘
               │
               ▼
      ┌─────────────────┐
      │    NER (Named   │  (Extracts names, locations, and dates)
      │  Entity Recog.) │
      └─────────────────┘
               │
               ▼
      ┌─────────────────┐
      │    Chunking     │  (Groups related words into phrases)
      └─────────────────┘
               │
               ▼
   [ Structured / Analyzed Text ]


## Tokenization
<h4>
    It is used to break document/text in smaller unit know as token. It is of Two types: 1) SentTokenizer and 2) WordTokenizer
</h4>

## Stemming
<h4>
    It is used to normalize the words into its base or root forms by removing suffixes.<br>
    eg:- Played - Play, Waited - Wait, Studying - Studi
</h4>

## Lemmatization
<h4>
    It is used to converts words into their meaningfull dictonary form, somehow it is similar to stemming but output of a lemmatization is a proper word<br>
  
</h4>

## POS tags
<h4>
    POS stands for parts of speach which is used to assign grammatical roles to the words<br>
    eg:- The(determinat) cat(noun) killed(verb) the(determinat) rat(noun)
</h4>

## NER 
<h4>
    It is a process of detecting named entity such as weather it is a person name, place, organization, location, quantity, etc.
</h4>

## Chunking
<h4>
    Picking individual piece of information and grouping them in a single phrase is know as chunking    
</h4>

In [1]:
import nltk

In [2]:
txt = "I Love mechatronics!. I love to eat paneer."
print(txt)

I Love mechatronics!. I love to eat paneer.


In [3]:
from nltk import sent_tokenize
sent_tokenize(txt)

['I Love mechatronics!.', 'I love to eat paneer.']

In [4]:
from nltk import word_tokenize
word_tokenize(txt)

['I',
 'Love',
 'mechatronics',
 '!',
 '.',
 'I',
 'love',
 'to',
 'eat',
 'paneer',
 '.']

## Stemming : it finds the nearest rootword by spech

In [5]:
from nltk.stem import PorterStemmer
ps = PorterStemmer()

In [6]:
ps.stem('CARS')

'car'

In [7]:
ps.stem('happiness')

'happi'

In [8]:
ps.stem('went')

'went'

In [9]:
ps.stem('studied')

'studi'

In [10]:
## Lemmatization: it finds the rearest the nearest rootword by 

In [11]:
from nltk.stem import WordNetLemmatizer
lm = WordNetLemmatizer()

In [12]:
lm.lemmatize('went', 'v')

'go'

In [13]:
lm.lemmatize('eaten', 'v')

'eat'

In [14]:
lm.lemmatize('studied', 'v')

'study'

In [15]:
lm.lemmatize('goodness', 'a')

'goodness'

In [16]:
#Stopwords - commonly words
from nltk.corpus import stopwords
stopwords.words('english')

['a',
 'about',
 'above',
 'after',
 'again',
 'against',
 'ain',
 'all',
 'am',
 'an',
 'and',
 'any',
 'are',
 'aren',
 "aren't",
 'as',
 'at',
 'be',
 'because',
 'been',
 'before',
 'being',
 'below',
 'between',
 'both',
 'but',
 'by',
 'can',
 'couldn',
 "couldn't",
 'd',
 'did',
 'didn',
 "didn't",
 'do',
 'does',
 'doesn',
 "doesn't",
 'doing',
 'don',
 "don't",
 'down',
 'during',
 'each',
 'few',
 'for',
 'from',
 'further',
 'had',
 'hadn',
 "hadn't",
 'has',
 'hasn',
 "hasn't",
 'have',
 'haven',
 "haven't",
 'having',
 'he',
 "he'd",
 "he'll",
 'her',
 'here',
 'hers',
 'herself',
 "he's",
 'him',
 'himself',
 'his',
 'how',
 'i',
 "i'd",
 'if',
 "i'll",
 "i'm",
 'in',
 'into',
 'is',
 'isn',
 "isn't",
 'it',
 "it'd",
 "it'll",
 "it's",
 'its',
 'itself',
 "i've",
 'just',
 'll',
 'm',
 'ma',
 'me',
 'mightn',
 "mightn't",
 'more',
 'most',
 'mustn',
 "mustn't",
 'my',
 'myself',
 'needn',
 "needn't",
 'no',
 'nor',
 'not',
 'now',
 'o',
 'of',
 'off',
 'on',
 'once',
 'on

In [17]:
stopwords.words('hinglish')

['a',
 'aadi',
 'aaj',
 'aap',
 'aapne',
 'aata',
 'aati',
 'aaya',
 'aaye',
 'ab',
 'abbe',
 'abbey',
 'abe',
 'abhi',
 'able',
 'about',
 'above',
 'accha',
 'according',
 'accordingly',
 'acha',
 'achcha',
 'across',
 'actually',
 'after',
 'afterwards',
 'again',
 'against',
 'agar',
 'ain',
 'aint',
 "ain't",
 'aisa',
 'aise',
 'aisi',
 'alag',
 'all',
 'allow',
 'allows',
 'almost',
 'alone',
 'along',
 'already',
 'also',
 'although',
 'always',
 'am',
 'among',
 'amongst',
 'an',
 'and',
 'andar',
 'another',
 'any',
 'anybody',
 'anyhow',
 'anyone',
 'anything',
 'anyway',
 'anyways',
 'anywhere',
 'ap',
 'apan',
 'apart',
 'apna',
 'apnaa',
 'apne',
 'apni',
 'appear',
 'are',
 'aren',
 'arent',
 "aren't",
 'around',
 'arre',
 'as',
 'aside',
 'ask',
 'asking',
 'at',
 'aur',
 'avum',
 'aya',
 'aye',
 'baad',
 'baar',
 'bad',
 'bahut',
 'bana',
 'banae',
 'banai',
 'banao',
 'banaya',
 'banaye',
 'banayi',
 'banda',
 'bande',
 'bandi',
 'bane',
 'bani',
 'bas',
 'bata',
 'bat

In [18]:
#pos tags - part of speech tags

In [19]:
txt = 'Mount Everet is the highest peak in the world'
print(txt)

Mount Everet is the highest peak in the world


In [20]:
txt_token = word_tokenize(txt)
txt_token

['Mount', 'Everet', 'is', 'the', 'highest', 'peak', 'in', 'the', 'world']

In [21]:
txt_tag = nltk.pos_tag(txt_token)
txt_tag

[('Mount', 'NNP'),
 ('Everet', 'NNP'),
 ('is', 'VBZ'),
 ('the', 'DT'),
 ('highest', 'JJS'),
 ('peak', 'NN'),
 ('in', 'IN'),
 ('the', 'DT'),
 ('world', 'NN')]

In [22]:
# ne_chucnk

In [23]:
txt = 'Narendra Modi is the Prime Minister of India'
print(txt)

Narendra Modi is the Prime Minister of India


In [24]:
txt_token = word_tokenize(txt)
txt_token

['Narendra', 'Modi', 'is', 'the', 'Prime', 'Minister', 'of', 'India']

In [25]:
txt_tag = nltk.pos_tag(txt_token)
txt_tag

[('Narendra', 'NNP'),
 ('Modi', 'NNP'),
 ('is', 'VBZ'),
 ('the', 'DT'),
 ('Prime', 'NNP'),
 ('Minister', 'NNP'),
 ('of', 'IN'),
 ('India', 'NNP')]

In [26]:
from nltk import ne_chunk
txt_chunk = ne_chunk(txt_tag)
print(txt_chunk)

(S
  (PERSON Narendra/NNP)
  (ORGANIZATION Modi/NNP)
  is/VBZ
  the/DT
  Prime/NNP
  Minister/NNP
  of/IN
  (GPE India/NNP))


# Vectorizer

### It is a technique used to convert text into numerical vectors show that mechine learning algorithim can process text data. It is of Two types : 1) count vertorizer, 2) TF-IDF vectorizer(TermFrequency-Inverse Document Frequency)

#### Count Vectorizer: Creates a vocabulary of all the unique words and counts how many times each word appers in a document

In [27]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
txt = ["I love Singing and I love Painting."]
x = cv.fit_transform(txt)

In [28]:
x

<1x4 sparse matrix of type '<class 'numpy.int64'>'
	with 4 stored elements in Compressed Sparse Row format>

In [29]:
print(x)

  (0, 1)	2
  (0, 3)	1
  (0, 0)	1
  (0, 2)	1


In [30]:
print(cv.vocabulary_)

{'love': 1, 'singing': 3, 'and': 0, 'painting': 2}


In [31]:
print(x.toarray())

[[1 2 1 1]]


In [32]:
txt = ["I love Singing and I love Painting.", "I love ice-cream"]
y = cv.fit_transform(txt)

In [33]:
y

<2x6 sparse matrix of type '<class 'numpy.int64'>'
	with 7 stored elements in Compressed Sparse Row format>

In [34]:
print(y)

  (0, 3)	2
  (0, 5)	1
  (0, 0)	1
  (0, 4)	1
  (1, 3)	1
  (1, 2)	1
  (1, 1)	1


In [35]:
print(cv.vocabulary_)

{'love': 3, 'singing': 5, 'and': 0, 'painting': 4, 'ice': 2, 'cream': 1}


In [36]:
print(y.toarray())

[[1 0 0 2 1 1]
 [0 1 1 1 0 0]]


## TF-IDF Vectorizer (Term Frequency - Inverse Document Frequency)

## TF - It is defind as the number of time a word apper in a document devided by total number of words in the document

In [37]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()
txt = ["I love Singing and I love Painting.", "I love ice-cream"]
z = tfidf.fit_transform(txt)

## IDF - Inverse Document Frequency :- It is defind as the log of total number of documents devided by the number of documents that containt the word

In [39]:
print(z)

  (0, 4)	0.44610080737655367
  (0, 0)	0.44610080737655367
  (0, 5)	0.44610080737655367
  (0, 3)	0.6348087971775132
  (1, 1)	0.6316672017376245
  (1, 2)	0.6316672017376245
  (1, 3)	0.4494364165239821


In [40]:
print(tfidf.vocabulary_)

{'love': 3, 'singing': 5, 'and': 0, 'painting': 4, 'ice': 2, 'cream': 1}


In [41]:
print(z.toarray())

[[0.44610081 0.         0.         0.6348088  0.44610081 0.44610081]
 [0.         0.6316672  0.6316672  0.44943642 0.         0.        ]]
