### NumPy- py library which is used to perform diff mathmetical operations on arrays.

In [1]:
# to import numpy
import numpy as np

In [2]:
np.__version__

'1.26.4'

In [3]:
# creating 1D array
# list to array
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [4]:
type(a)

numpy.ndarray

In [5]:
a = np.array([1, 2.3, 3, 4, 5, False])
a

array([1. , 2.3, 3. , 4. , 5. , 0. ])

In [6]:
a = np.array([24,'dog',False,4.6])
a

array(['24', 'dog', 'False', '4.6'], dtype='<U32')

In [7]:
a = np.array(['cat', 'bat', '2.5'])
a

array(['cat', 'bat', '2.5'], dtype='<U3')

In [9]:
a = np.array([25, 2.5, True])
print(a)

[25.   2.5  1. ]


In [10]:
t = np.array((10, 20, 30, 40, 50))
t

array([10, 20, 30, 40, 50])

In [11]:
s = np.array({1,1,1,2,2,4,4,3,3,3})
s

array({1, 2, 3, 4}, dtype=object)

In [12]:
d = np.array({'a':1, 'b':2, 'c':3}) #dictonary to array
d

array({'a': 1, 'b': 2, 'c': 3}, dtype=object)