## Creating 2D-Array

In [2]:
import numpy as np

In [3]:
a = np.array([[1,2,3],
              [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
a = np.array([(1,2,3),
              (4,5,6)])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
b = np.array([[1,3,5,7],
              [2,4,6,8],
              [9,2,7,1]])
b

array([[1, 3, 5, 7],
       [2, 4, 6, 8],
       [9, 2, 7, 1]])

In [6]:
#Array attributes
#shape - returns the shape of the array
b.shape

(3, 4)

In [7]:
b.size

12

In [8]:
b.ndim

2

In [9]:
a = np.array([[[[[1,2,3]]]]])
a.ndim

5

In [12]:
# 
a = np.array([1,2,3], ndmin=32)
a

array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1, 2,
                                      3]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]])

In [17]:
a = np.array([1,2,3],ndmin=33)
a

ValueError: ndmin bigger than allowable number of dimensions NPY_MAXDIMS (=32)

In [18]:
print(np.MAXDIMS)

32


In [21]:
#arange - it returns a 1D Array of given range
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [23]:
np.arange(10,0,-2)

array([10,  8,  6,  4,  2])

In [24]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [26]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
np.zeros((5,5)).astype(int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [30]:
np.zeros((5,5),dtype='int')

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [33]:
#ones
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [34]:
np.ones((10,10), dtype='int')

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])