## Creating 2D-Array

In [2]:
import numpy as np

In [3]:
a = np.array([[1,2,3],
              [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
a = np.array([(1,2,3),
              (4,5,6)])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
b = np.array([[1,3,5,7],
              [2,4,6,8],
              [9,2,7,1]])
b

array([[1, 3, 5, 7],
       [2, 4, 6, 8],
       [9, 2, 7, 1]])

In [6]:
#Array attributes
#shape - returns the shape of the array
b.shape

(3, 4)

In [7]:
b.size

12

In [8]:
b.ndim

2

In [9]:
a = np.array([[[[[1,2,3]]]]])
a.ndim

5

In [12]:
# 
a = np.array([1,2,3], ndmin=32)
a

array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1, 2,
                                      3]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]])

In [17]:
a = np.array([1,2,3],ndmin=33)
a

ValueError: ndmin bigger than allowable number of dimensions NPY_MAXDIMS (=32)

In [18]:
print(np.MAXDIMS)

32


In [21]:
#arange - it returns a 1D Array of given range
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [23]:
np.arange(10,0,-2)

array([10,  8,  6,  4,  2])

In [24]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [26]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [28]:
np.zeros((5,5)).astype(int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [30]:
np.zeros((5,5),dtype='int')

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [33]:
#ones
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [34]:
np.ones((10,10), dtype='int')

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [36]:
np.full((5,5),8)

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [39]:
np.full((5,5),'👽')

array([['👽', '👽', '👽', '👽', '👽'],
       ['👽', '👽', '👽', '👽', '👽'],
       ['👽', '👽', '👽', '👽', '👽'],
       ['👽', '👽', '👽', '👽', '👽'],
       ['👽', '👽', '👽', '👽', '👽']], dtype='<U1')

In [41]:
np.eye(5) #identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [42]:
np.eye(5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [45]:
#linspace - returns equally distributed number
np.linspace(1,100,11,dtype=int)

array([  1,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [47]:
np.linspace(1,100,3, dtype=int)

array([  1,  50, 100])

In [48]:
np.linspace(0,100,11, dtype=int)

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [49]:
#Random Numbers
#Returns a random value between 0 & 1
np.random.rand()

0.6550684645532873

In [57]:
a = 1 + np.random.rand() * 99
a

95.98284577054275

In [58]:
np.random.rand(4)

array([0.88347271, 0.67766323, 0.08257541, 0.03209892])

In [59]:
np.random.rand(3,4)

array([[0.61666722, 0.04526868, 0.28466016, 0.27777092],
       [0.98427878, 0.96319611, 0.12456109, 0.84578223],
       [0.31901872, 0.08237198, 0.56897137, 0.2686581 ]])

In [62]:
np.random.randint(1,20) #return random number between given range

9

In [63]:
np.random.randint(1,20, size=8)

array([16,  6,  1,  9, 14,  3,  6, 10])

In [65]:
np.random.randint(1,20, 8)

array([ 1,  6,  9, 11,  4, 16, 11, 14])

In [67]:
np.random.randint(1,20,(2,3))

array([[14, 19, 14],
       [12, 11, 14]])

In [70]:
b = np.array(['good', 'better', 'best'])

In [85]:
b[np.random.randint(0,2)]

'better'

## Mathmetical Functions

In [ ]:
a = np.