## Creating 2D-Array

In [1]:
import numpy as np

In [2]:
a = np.array([[1,2,3],
              [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
a = np.array([(1,2,3),
              (4,5,6)])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [4]:
b = np.array([[1,3,5,7],
              [2,4,6,8],
              [9,2,7,1]])
b

array([[1, 3, 5, 7],
       [2, 4, 6, 8],
       [9, 2, 7, 1]])

In [5]:
#Array attributes
#shape - returns the shape of the array
b.shape

(3, 4)

In [6]:
b.size

12

In [7]:
b.ndim

2

In [8]:
a = np.array([[[[[1,2,3]]]]])
a.ndim

5

In [9]:
# 
a = np.array([1,2,3], ndmin=32)
a

array([[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[[1, 2,
                                      3]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]]])

In [10]:
a = np.array([1,2,3],ndmin=33)
a

ValueError: ndmin bigger than allowable number of dimensions NPY_MAXDIMS (=32)

In [ ]:
print(np.MAXDIMS)

In [ ]:
#arange - it returns a 1D Array of given range
np.arange(1,11)

In [11]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [12]:
np.arange(10,0,-2)

array([10,  8,  6,  4,  2])

In [13]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [14]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [15]:
np.zeros((5,5)).astype(int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [16]:
np.zeros((5,5),dtype='int')

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [17]:
#ones
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [18]:
np.ones((10,10), dtype='int')

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [19]:
np.full((5,5),8)

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [20]:
np.full((5,5),'👽')

array([['👽', '👽', '👽', '👽', '👽'],
       ['👽', '👽', '👽', '👽', '👽'],
       ['👽', '👽', '👽', '👽', '👽'],
       ['👽', '👽', '👽', '👽', '👽'],
       ['👽', '👽', '👽', '👽', '👽']], dtype='<U1')

In [21]:
np.eye(5) #identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
np.eye(5, dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

In [23]:
#linspace - returns equally distributed number
np.linspace(1,100,11,dtype=int)

array([  1,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [24]:
np.linspace(1,100,3, dtype=int)

array([  1,  50, 100])

In [25]:
np.linspace(0,100,11, dtype=int)

array([  0,  10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [26]:
#Random Numbers
#Returns a random value between 0 & 1
np.random.rand()

0.7880053748979027

In [27]:
a = 1 + np.random.rand() * 99
a

89.22201734602103

In [28]:
np.random.rand(4)

array([0.40898154, 0.0617005 , 0.45064752, 0.25343021])

In [29]:
np.random.rand(3,4)

array([[0.31084745, 0.27023228, 0.62053154, 0.68434994],
       [0.73175624, 0.30571159, 0.63007953, 0.38125248],
       [0.58396633, 0.93142388, 0.10697865, 0.31777227]])

In [30]:
np.random.randint(1,20) #return random number between given range

10

In [31]:
np.random.randint(1,20, size=8)

array([ 6,  5, 17, 16,  7,  5, 12,  5])

In [32]:
np.random.randint(1,20, 8)

array([ 1,  3, 10,  4,  9,  5, 17,  9])

In [33]:
np.random.randint(1,20,(2,3))

array([[ 4, 13, 11],
       [17, 13,  8]])

In [34]:
b = np.array(['good', 'better', 'best'])

In [35]:
b[np.random.randint(0,2)]

'good'

## Mathmetical Functions

In [36]:
a = np.array([23,75,57,50,81])
b = np.array([4,8,6,5,9])

In [37]:
a + b

array([27, 83, 63, 55, 90])

In [38]:
#add - Addition
np.add(a,b)

array([27, 83, 63, 55, 90])

In [39]:
a-b

array([19, 67, 51, 45, 72])

In [40]:
np.subtract(a,b)

array([19, 67, 51, 45, 72])

In [41]:
np.multiply(a,b)

array([ 92, 600, 342, 250, 729])

In [42]:
np.divide(a,b)

array([ 5.75 ,  9.375,  9.5  , 10.   ,  9.   ])

In [43]:
np.floor_divide(a,b)

array([ 5,  9,  9, 10,  9])

In [44]:
np.mod(a,b) 

array([3, 3, 3, 0, 0])

In [45]:
np.divmod(a,b) #floor_divide and mod

(array([ 5,  9,  9, 10,  9]), array([3, 3, 3, 0, 0]))

In [46]:
np.log(a) # log - by default with base = 'e'

array([3.13549422, 4.31748811, 4.04305127, 3.91202301, 4.39444915])

In [47]:
np.log10(a) # log with base=10

array([1.36172784, 1.87506126, 1.75587486, 1.69897   , 1.90848502])

In [48]:
np.sqrt(a)

array([4.79583152, 8.66025404, 7.54983444, 7.07106781, 9.        ])

In [49]:
np.cbrt(a)

array([2.84386698, 4.21716333, 3.84850113, 3.6840315 , 4.32674871])

In [50]:
np.power(b,2)

array([16, 64, 36, 25, 81], dtype=int32)

In [51]:
np.sin(a) #Trigonometry - here it returns the value

array([-0.8462204 , -0.38778164,  0.43616476, -0.26237485, -0.62988799])

In [52]:
np.sin(90)

0.8939966636005579

In [53]:
np.sin(90 * (np.pi/180))

1.0

In [54]:
#cos
np.cos(a)

array([-0.53283302,  0.92175127,  0.89986683,  0.96496603,  0.77668598])

In [55]:
#tan
np.tan(a)

array([ 1.58815308, -0.42070095,  0.48469923, -0.27190061, -0.81099442])

In [56]:
1/np.tan(a)

array([ 0.62966222, -2.37698536,  2.06313513, -3.67781445, -1.23305411])

In [57]:
1/np.cos(a)

array([-1.87676056,  1.08489137,  1.11127555,  1.03630591,  1.28752163])

In [58]:
1/np.sin(a)

array([-1.18172523, -2.57877091,  2.29271161, -3.81134086, -1.58758384])

## Statistical Functions

In [59]:
a = np.array([45,67,20,58,25])
a

array([45, 67, 20, 58, 25])

In [60]:
np.max(a)

67

In [61]:
np.min(a)

20

In [62]:
np.argmax(a) #returns index position of maximum value

1

In [63]:
np.argmin(a) #returns index position of minimum value

2

In [64]:
np.sort(a) #ascending order

array([20, 25, 45, 58, 67])

In [65]:
np.sort(a)

array([20, 25, 45, 58, 67])

In [66]:
np.argsort(a)  #index position of order

array([2, 4, 0, 3, 1], dtype=int64)

In [67]:
np.flip(a)

array([25, 58, 20, 67, 45])

In [68]:
np.flip(np.sort(a))

array([67, 58, 45, 25, 20])

In [69]:
np.mean(a)

43.0

In [70]:
np.median(a)

45.0

In [71]:
np.std(a) # standard deviation = root over of variance

18.20988742414406

In [72]:
np.var(a) #variance

331.6

In [73]:
np.cumsum(b) # Cumlative Summation

array([ 4, 12, 18, 23, 32])

In [74]:
np.cumprod(b) # Cumlative Product

array([   4,   32,  192,  960, 8640])

In [75]:
np.cumproduct(b)

array([   4,   32,  192,  960, 8640])

In [76]:
a = np.array([1,2,3,4])
np.repeat(a, 4)

array([1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 4, 4, 4, 4])

In [77]:
np.tile(a,4)

array([1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4])

In [78]:
#where
a = np.array([1,2,3,4,5,4,4,6,4])
np.where(a==4)

(array([3, 5, 6, 8], dtype=int64),)

In [79]:
np.round(24.6)

25.0

In [80]:
np.ceil(25.1)

26.0

In [81]:
np.trunc(25.9)

25.0