## Vector Maths

In [2]:
import numpy as np

In [7]:
a = np.array([[1,3],
              [2,4]])
b = np.array([[5,7],
              [6,9]])

print(a)
print(b)

[[1 3]
 [2 4]]
[[5 7]
 [6 9]]


In [8]:
# dot
np.dot(a,b)

array([[23, 34],
       [34, 50]])

In [10]:
a@b #dot product

array([[23, 34],
       [34, 50]])

In [9]:
# cross
np.cross(a,b)

array([-8, -6])

In [11]:
# transpose
np.transpose(a)

array([[1, 2],
       [3, 4]])

In [13]:
a.T   # transpose

array([[1, 2],
       [3, 4]])

In [14]:
#Indexing and Slicing in 1D array
a = np.array([45,78,25,99,66])
a

array([45, 78, 25, 99, 66])

In [15]:
#indexing
#Syntax : var[index_postion]
a[2]

25

In [16]:
a[-3]

25

In [17]:
# Slicing
a[::2]

array([45, 25, 66])

In [18]:
# Indexing and Slicing in 2D Array
b = np.random.randint(1,20,(5,5))
b

array([[ 5,  1,  5, 17, 19],
       [11,  1, 17, 19, 19],
       [14, 15,  4, 17, 18],
       [19,  4,  7, 14,  2],
       [ 1, 19, 14,  4,  4]])

In [19]:
#indexing
#Syntax : var[row_index, col_index]
b[2,3]

17

In [21]:
b[3] #bydefault row

array([19,  4,  7, 14,  2])

In [24]:
np.where(b==11)

(array([1], dtype=int64), array([0], dtype=int64))

In [25]:
np.where(b==17)

(array([0, 1, 2], dtype=int64), array([3, 2, 3], dtype=int64))

In [26]:
## Slicing
## Syntax: var[row_slicing, col_slicing]
b[1:4:1, 1:4:1]

array([[ 1, 17, 19],
       [15,  4, 17],
       [ 4,  7, 14]])

In [27]:
## Concatination
a = np.random.randint(1, 20, (2,2))
a

array([[ 9,  2],
       [11, 18]])

In [29]:
b = np.random.randint(1, 20,(2,4))
b

array([[ 7,  8,  5,  5],
       [ 3, 17, 13, 15]])

In [30]:
c = np.random.randint(1, 20,(4,4))
c

array([[13,  4,  3, 16],
       [ 1, 13, 10, 11],
       [ 4, 18,  3,  6],
       [ 5,  3,  5, 18]])

In [31]:
# axis = 1 ()
np.concatenate((a,b))

ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 2 and the array at index 1 has size 4